[ag]
population_size = 10
num_parents = 5
selection_method = 'ranking'
elite_size = 2
mutation_rate = 0.5
crossover_rate = 90
crossover_method = 'uniform'
[passcode]
#correct_passcode = '234AHLp91n'
correct_passcode = '2622525252'
